audiencias.globals.dependencyAutocomplete = ['Presidencia de la nación',
'Vicepresidencia',
'Secretaría general',
'Subsecretaría de coordinación',
'Coordinador general de asuntos presidenciales',
'Subsecretaría general',
'Subsecretaría de relaciones con la sociedad civil',
'Casa militar',
'Secretaría legal y técnica',
'Subsecretaría de asuntos legales',
'Subsecretaría técnica',
'Agencia federal de inteligencia',
'Secretaría de programación para la prevención de la drogadicción y la lucha contra el narcotráfico (sedronar)',
'Subsecretaría de diseño, monitoreo y evaluación de abordaje territorial, relaciones internacionales y control de precursores químicos',
'Subsecretaría de prevención, capacitación y asistencia de las adicciones',
'Subsecretaría de coordinación administrativa',
'Jefatura de gabinete de ministros',
'Secretaría de asuntos estrátegicos',
'Subsecretaría de asuntos globales',
'Subsecretaría de asuntos institucionales',
'Secretaría de coordinación de políticas públicas',
'Subsecretaría de evaluación del presupuesto nacional',
'Secretaría de comunicación pública',
'Subsecretaría de comunicación pública',
'Subsecretaría de comunicación y contenidos de difusión',
'Subsecretaría de vínculo ciudadano',
'Estado argentino en la nueva televisión del sur (telesur)',
'Secretaría de coordinación interministerial',
'Subsecretaría de evaluación de proyectos con financiamiento externo',
'Secretaría de relaciones parlamentarias y administración',
'Subsecretaria de relaciones parlamentarias',
'Subsecretaria de coordinación administrativa',
'Sistema federal de medios y contenidos públicos',
'Secretaría de contenidos públicos',
'Subsecretaría de centros temáticos y expresiones federales',
'Secretaría de medios públicos',
'Unidad plan belgrano',
'Agencia de administración de bienes del estado (d)',
'Ministerio del interior, obras públicas y vivienda',
'Subsecretaría de coordinación de obra pública federal',
'Subsecretaría de planificación territorial de la inversión pública',
'Secretaría de vivienda y hábitat',
'Subsecretaría de hábitat y desarrollo humano',
'Subsecretaría de desarrollo urbano y vivienda',
'Secretaría de asuntos municipales',
'Subsecretaría de gestión municipal',
'Secretaría de interior',
'Subsecretaría de interior',
'Secretaría de asuntos políticos y fortalecimiento institucional',
'Subsecretaría de asuntos políticos',
'Subsecretaría de asuntos electorales',
'Subsecretaría de reforma institucional y fortalecimiento de la democracia',
'Secretaría de provincias',
'Subsecretaría de relaciones con las provincias',
'Subsecretaría de desarrollo provincial',
'Secretaría de obras públicas',
'Subsecretaría de recursos hídricos',
'Subsecretaría de obras públicas',
'Ministerio de relaciones exteriores y culto',
'Secretaría de coordinación y cooperación internacional',
'Subsecretaría de coordinación y cooperación internacional',
'Secretaría de comercio y relaciones económicas internacionales',
'Subsecretaría de negociaciones económicas internacionales',
'Subsecretaría de integración económica americana y mercosur',
'Subsecretaría de promoción comercial y desarrollo de inversiones',
'Secretaría de relaciones exteriores',
'Subsecretaría de asuntos de américa latina y el caribe',
'Subsecretaría de relaciones exteriores',
'Subsecretaría de malvinas y atlántico sur',
'Secretaría de culto',
'Subsecretaría de culto',
'Ministerio de defensa',
'Secretaría de servicios logísticos para la defensa y coordinación militar en emergencias',
'Subsecretaría de coordinación militar en emergencias',
'Subsecretaría de servicio logístico de la defensa',
'Subsecretaría de patrimonio cultural y relaciones con la comunidad',
'Secretaría de ciencia, tecnología y producción para la defensa',
'Subsecretaría de gestión y planificación para la defensa',
'Subsecretaría de investigación, desarrollo y producción para la defensa',
'Subsecretaría de ciberdefensa',
'Secretaría de estrategia y asuntos militares',
'Subsecretaría de formación',
'Subsecretaría de planeamiento estratégico y política militar',
'Subsecretaría de asuntos internacionales de la defensa',
'Ministerio de hacienda y finanzas públicas',
'Secretaría de finanzas',
'Subsecretaría de financiamiento',
'Subsecretaría de relaciones financieras internacionales',
'Secretaría de política económica y planificación del desarrollo',
'Subsecretaría de programación macroeconómica',
'Subsecretaría de planificación económica',
'Subsecretaría de desarrollo',
'Secretaría legal y administrativa',
'Subsecretaría de administración y normalización patrimonial',
'Subsecretaría legal',
'Secretaría de hacienda',
'Subsecretaría de presupuesto',
'Subssubsecretaría de coordinación provincial',
'Subsecretaría de ingresos públicos',
'Ministerio de producción',
'Secretaría de integración productiva',
'Subsecretaría de desarrollo institucional productivo',
'Subsecretaría de integración de políticas productivas',
'Secretaría de comercio',
'Subsecretaría de comercio interior',
'Subsecretaría de comercio exterior',
'Secretaría de emprendedores y de la pequeña y mediana empresa',
'Subsecretaría de emprendedores',
'Subsecretaría de política y gestión de la pequeña y mediana empresa',
'Subsecretaría de financiamiento de la producción',
'Secretaría de industrias y servicios',
'Subsecretaría de industria',
'Subsecretaría de gestión productiva',
'Subsecretaría de servicios tecnológicos y productivos',
'Secretaría de la transformación productiva',
'Subsecretaría de políticas de desarrollo productivo',
'Subsecretaría de desarrollo y planeamiento productivo',
'Subsecretaría de articulación federal y sectorial',
'Ministerio de agroindustria',
'Subsecretaría de coordinación técnica y administrativa',
'Subsecretaría de comunicación institucional',
'Secretaría de coordinación y desarrollo territorial',
'Subsecretaría de desarrollo territorial',
'Subsecretaría de coordinación institucional',
'Subsecretaría de coordinación política',
'Secretaría de agricultura, ganadería y pesca',
'Subsecretaría de agricultura',
'Subsecretaría de ganadería',
'Subsecretaría de lechería',
'Subsecretaría de pesca y acuicultura',
'Subsecretaría de desarrollo foresto industrial',
'Secretaría de agregado de valor',
'Subsecretaría de bioindustria',
'Subsecretaría de alimentos y bebidas',
'Secretaría de mercados agroindustriales',
'Subsecretaría de mercados agropecuarios',
'Subsecretaría de información y estadística pública',
'Secretaría de agricultura familiar',
'Subsecretaría de ejecución de programas para la agricultura familiar',
'Ministerio de turismo',
'Subsecretaría de inversiones turísticas',
'Secretaría de innovación, tecnología y calidad turística',
'Subsecretaría de calidad turística',
'Subsecretaría de innovación y tecnología',
'Secretaría de turismo',
'Subsecretaría de desarrollo turístico',
'Subsecretaría de promoción turística nacional',
'Ministerio de transporte',
'Secretaría de obras de transporte',
'Subsecretaría de contratación y ejecución de obras',
'Subsecretaría de supervisión y control de obras',
'Secretaría de gestión del transporte',
'Subsecretaría de gestión administrativa de transporte',
'Subsecretaría de transporte ferroviario',
'Subsecretaría de transporte automotor',
'Subsecretaría de puertos y vías navegables',
'Secretaría de planificación del transporte',
'Subsecretaría de movilidad urbana',
'Subsecretaría de planificación y coordinación de transporte',
'Subsecretaría de planificación de transporte de cargas y logística',
'Subsecretaría de planificación de transporte interurbano e internacional de pasajeros',
'Ministerio de justicia y derechos humanos',
'Subsecretaría de asuntos registrales',
'Secretaría de justicia',
'Subsecretaría de relaciones con el poder judicial y asuntos penitenciarios',
'Subsecretaría de política criminal',
'Subsecretaría de acceso a la justicia',
'Secretaría de derechos humanos y pluralismo cultural',
'Subsecretaría de protección de derechos humanos',
'Subsecretaría de promoción de derechos humanos',
'Consejo federal de derechos humanos',
'Secretaría de planificación estratégica',
'Oficina anticorrupción',
'Escribanía general del gobierno de la nación',
'Ministerio de seguridad',
'Secretaría de coordinación, planeamiento y formación',
'Subsecretaría de asuntos jurídicos',
'Subsecretaría de planeamiento y formación',
'Secretaría de seguridad',
'Subsecretaría de políticas de seguridad e intervención territorial',
'Subsecretaría de logística',
'Subsecretaría de participación ciudadana',
'Subsecretaría de lucha contra el narcotráfico',
'Subsecretaría de investigación del delito organizado y complejo',
'Secretaría de cooperación con los poderes judiciales, ministerios públicos y legislaturas',
'Subsecretaría de articulación con los poderes judiciales y los ministerios públicos',
'Subsecretaría de articulación legislativa',
'Secretaría de protección civil y abordaje integral de emergencias y catástrofes',
'Subsecretaría de gestión integral de riesgo de desastres',
'Subsecretaría de protección civil',
'Secretaría de seguridad interior',
'Subsecretaría de logística federal',
'Subsecretaría de capacitación, formación y programas de seguridad',
'Subsecretaría de estadística criminal',
'Secretaría de fronteras',
'Subsecretaría de desarrollo de frontera',
'Ministerio de trabajo, empleo y seguridad social',
'Subsecretaría de planificación de políticas socio laborales',
'Subsecretaría de programación técnica y estudios laborales',
'Secretaría de seguridad social',
'Subsecretaría de políticas de la seguridad social',
'Subsecretaría de coordinación de los regímenes de la seguridad social',
'Secretaría de trabajo',
'Subsecretaría de relaciones laborales',
'Subsecretaría de fiscalización del trabajo y de la seguridad social',
'Secretaría de empleo',
'Subsecretaría de políticas de empleo y formación profesional',
'Subsecretaría de promoción del sector social de la economía',
'Ministerio de desarrollo social',
'Secretaría de coordinación y monitoreo institucional',
'Subsecretaría de coordinación, monitoreo y logística',
'Secretaría de gestión y articulación institucional',
'Subsecretaría de abordaje territorial',
'Subsecretaría de organización comunitaria',
'Subsecretaría de políticas alimentarias',
'Secretaría de organización y comunicación comunitaria',
'Subsecretaría de planificación y comunicación estratégica',
'Subsecretaría de comercialización de la economía social',
'Subsecretaría de juventud',
'Secretaría de economía social',
'Subsecretaría de fortalecimiento institucional',
'Subsecretaría de organización de ingresos sociales',
'Subsecretaría de responsabilidad social',
'Secretaría nacional de niñez, adolescencia y familia',
'Subsecretaría de desarrollo institucional e integración federal',
'Subsecretaría de derechos para la niñez, adolescencia y familia',
'Ministerio de salud',
'Secretaría de promoción, programas sanitarios y salud comunitaria',
'Subsecretaría de prevención y control de riesgos',
'Subsecretaría de atención primaria de la salud',
'Secretaría de relaciones nacionales e internacionales',
'Subsecretaría de relaciones institucionales',
'Secretaría de políticas, regulación e institutos',
'Subsecretaría de políticas, regulación y fiscalización',
'Subsecretaría de gestión de servicios asistenciales',
'Ministerio de educación y deportes',
'Subsecretaría de enlace y cooperación intersectorial e institucional',
'Secretaría general del consejo federal de educación',
'Secretaría de innovación y calidad educativa',
'Subsecretaría de innovación y mejora de los aprendizajes',
'Secretaría de gestión educativa',
'Subsecretaría de gestión y políticas socioeducativas',
'Secretaría de deporte, educación física y recreación',
'Subsecretaría de deportes y alto rendimiento deportivo',
'Subsecretaría de educación física, recreación e infraestructura',
'Secretaría de políticas universitarias',
'Subsecretaría de gestión y coordinación de políticas universitarias',
'Secretaría de evaluación educativa',
'Ministerio de ciencia, tecnología e innovación productiva',
'Secretaría de planeamiento y políticas en ciencia, tecnología e innovación productiva',
'Subsecretaría de políticas en ciencia, tecnología e innovación productiva',
'Subsecretaría de estudios y prospectiva',
'Secretaría de articulación científico-tecnológica',
'Subsecretaría de evaluación institucional',
'Ministerio de cultura',
'Secretaría de patrimonio cultural',
'Subsecretaría de gestión patrimonial',
'Secretaría de cultura y creatividad',
'Subsecretaría de cultura ciudadana',
'Subsecretaría de economía creativa',
'Secretaría de integración federal y cooperación internacional',
'Subsecretaría de cooperación cultural',
'Ministerio de ambiente y desarrollo sustentable',
'Secretaría de política ambiental, cambio climático, ambiente y desarrollo sustentable',
'Subsecretaría de planificación y ordenamiento ambiental del territorio',
'Subsecretaría de cambio climático y desarrollo sustentable',
'Secretaría de coordinación interjurisdiccional',
'Secretaría de control y monitoreo ambiental',
'Subsecretaría de control y fiscalización ambiental y prevención de la contaminación',
'Ministerio de modernización',
'Subsecretaría de relaciones laborales y fortalecimiento del servicio civil',
'Subsecretaría de tecnología y ciberseguridad',
'Subsecretaría de telecomunicaciones y redes públicas',
'Secretaría de empleo público',
'Subsecretaría de planificación de empleo público',
'Secretaría país digital',
'Subsecretaría desarrollo de país digital',
'Secretaría de gestión e innovación pública',
'Subsecretaría de gobierno digital',
'Subsecretaría de innovación pública y gobierno abierto',
'Secretaría de modernización administrativa',
'Subsecretaría de gestión administrativa',
'Ministerio de energía y minería',
'Subsecretaría de coordinación de política tarifaria',
'Secretaría de energía eléctrica',
'Subsecretaría de energías renovables',
'Subsecretaría de energía hidroeléctrica',
'Subsecretaría de energía nuclear',
'Subsecretaría de energía térmica, transporte y distribución de energía eléctrica',
'Secretaría de minería',
'Subsecretaría de desarrollo minero',
'Subsecretaría de política minera',
'Secretaría de recursos hidrocarburíferos',
'Subsecretaría de exploración y producción',
'Subsecretaría de refinación y comercialización',
'Secretaría de planeamiento energético estratégico',
'Subsecretaría de escenarios y evaluación de proyectos',
'Subsecretaría de ahorro y eficiencia energética',
'Subsecretaría de infraestructura energética',
'Ministerio de comunicaciones',
'Secretaría de tecnologías de la información y las comunicaciones',
'Subsecretaría de regulación',
'Subsecretaría de planeamiento',
'Secretaría de promoción de inversiones']